import type { Metadata } from 'next';

import './globals.css';
import Header from './header';

export const metadata: Metadata = {
  title: 'Create Next Blog',
  description: 'Generated by create next blog',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='ko'>
      <body>
        <Header />
        {children}
      </body>
    </html>
  );
}
